# Generated by Django 5.0.9 on 2025-01-12 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_alter_inventoryitem_unique_together"),
        ("sales", "0005_returnitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="warehouse",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.warehouse",
            ),
        ),
    ]
