# Generated by Django 5.0.9 on 2025-01-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requisition", "0030_alter_requisition_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="requisitionitem",
            name="is_new_item",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this is a request for a new item not in inventory",
            ),
        ),
    ]
