# Generated by Django 5.0.9 on 2025-01-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requisition", "0031_requisitionitem_is_new_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="requisition",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
