# Generated by Django 5.1.4 on 2025-01-10 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_pendingpoitem_brand'),
        ('requisition', '0033_alter_requisition_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='destination_warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_deliveries', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='source_warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_deliveries', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
