# Generated by Django 5.1.4 on 2024-12-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_globalsettings_inventoryitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='location',
            field=models.CharField(choices=[('attendant_warehouse', 'Attendant Warehouse'), ('manager_warehouse', 'Manager Warehouse')], default='attendant_warehouse', max_length=50),
        ),
    ]
