# Generated by Django 5.0.9 on 2025-01-09 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_update_warehouse_field"),
        ("requisition", "0033_alter_requisition_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingPOItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_processed", models.BooleanField(default=False)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.brand",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="requisition.requisitionitem",
                    ),
                ),
            ],
            options={
                "ordering": ["brand", "created_at"],
            },
        ),
    ]
