# Generated by Django 5.1.4 on 2025-01-10 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_pendingpoitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingpoitem",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_pending_items",
                to="inventory.brand",
            ),
        ),
    ]
