# Generated by Django 5.1.4 on 2025-01-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_pendingpoitem_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
