# Generated by Django 5.0.9 on 2025-01-12 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_inventoryitem_last_updated"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inventoryitem",
            unique_together={("brand", "model")},
        ),
    ]
