# Generated by Django 5.0.9 on 2025-01-12 11:07

from django.db import migrations
from django.db.models import Min

def handle_duplicates(apps, schema_editor):
    InventoryItem = apps.get_model('inventory', 'InventoryItem')
    # Find duplicates
    duplicates = (
        InventoryItem.objects.values('brand', 'model', 'warehouse')
        .annotate(min_id=Min('id'))
        .filter(id__gt=Min('id'))
    )
    # Delete all duplicates except the first one
    for dup in duplicates:
        InventoryItem.objects.filter(
            brand=dup['brand'],
            model=dup['model'],
            warehouse=dup['warehouse']
        ).exclude(id=dup['min_id']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_inventoryitem_last_updated"),
    ]

    operations = [
        migrations.RunPython(handle_duplicates),
        migrations.AlterUniqueTogether(
            name="inventoryitem",
            unique_together={("brand", "model", "warehouse")},
        ),
    ]
