# Generated by Django 5.0.9 on 2025-01-12 11:07

from django.db import migrations

def handle_duplicates(apps, schema_editor):
    # Use raw SQL to delete duplicates, keeping only the one with the minimum ID
    schema_editor.execute("""
        WITH duplicates AS (
            SELECT id,
                   ROW_NUMBER() OVER (PARTITION BY brand_id, model, warehouse_id ORDER BY id) as row_num
            FROM inventory_inventoryitem
        )
        DELETE FROM inventory_inventoryitem
        WHERE id IN (
            SELECT id FROM duplicates WHERE row_num > 1
        );
    """)

class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_inventoryitem_last_updated"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inventoryitem",
            unique_together=set(),  # Remove any existing unique_together constraints
        ),
        migrations.RunPython(handle_duplicates),
        migrations.AlterUniqueTogether(
            name="inventoryitem",
            unique_together={("brand", "model", "warehouse")},
        ),
    ]
