# Generated by Django 5.0.9 on 2025-01-12 11:07

from django.db import migrations

def handle_duplicates(apps, schema_editor):
    # Use raw SQL to delete duplicates, keeping only the one with the minimum ID
    schema_editor.execute("""
        DELETE FROM inventory_inventoryitem a
        WHERE EXISTS (
            SELECT 1 FROM inventory_inventoryitem b
            WHERE b.brand_id = a.brand_id
            AND b.model = a.model
            AND b.warehouse_id = a.warehouse_id
            AND b.id < a.id
        );
    """)

class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_alter_inventoryitem_unique_together"),
    ]

    operations = [
        migrations.RunPython(handle_duplicates),
    ]
