# Generated by Django 5.0.9 on 2025-01-12 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_alter_inventoryitem_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inventoryitem",
            unique_together=set(),
        ),
    ]
