# Generated by Django 5.0.9 on 2025-01-12 11:07

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_handle_duplicates"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inventoryitem",
            unique_together={("brand", "model", "warehouse")},
        ),
    ]
