# Generated by Django 5.0.9 on 2025-01-13 00:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0015_alter_inventoryitem_unique_together"),
        ("inventory", "0016_add_unique_constraint"),
    ]

    operations = []
