# Generated by Django 5.1.4 on 2025-01-04 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventoryitem_location'),
        ('purchasing', '0015_alter_delivery_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='inventory.warehouse'),
        ),
    ]
