# Generated by Django 5.0.9 on 2025-01-04 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0017_fix_subtotal"),
    ]

    operations = []
