# Generated by Django 5.0.9 on 2025-01-04 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0018_auto_20250104_1350"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorderitem",
            name="subtotal",
        ),
    ]
