# Generated by Django 5.0.9 on 2025-01-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0019_remove_purchaseorderitem_subtotal"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderitem",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
