# Generated by Django 5.1.4 on 2025-01-04 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0021_auto_20250104_1400"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorderitem",
            name="subtotal",
        ),
    ]
