# Generated by Django 5.0.9 on 2025-01-07 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0016_alter_delivery_warehouse"),
        ("purchasing", "0022_remove_purchaseorderitem_subtotal"),
    ]

    operations = []
