# Generated by Django 5.0.9 on 2025-01-07 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0023_merge_20250107_1928"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delivery",
            name="warehouse",
        ),
    ]
