# Generated by Django 5.0.9 on 2025-01-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0026_pendingpoitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingpoitem",
            name="is_processed",
            field=models.BooleanField(default=False),
        ),
    ]
