# Generated by Django 5.1.4 on 2025-01-11 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_pendingpoitem_brand'),
        ('purchasing', '0028_alter_pendingpoitem_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='item_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem'),
        ),
    ]
