# Generated by Django 5.0.9 on 2025-01-12 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0030_fix_subtotal_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorderitem",
            name="subtotal",
        ),
    ]
